vim.opt.allowrevins = true
vim.opt.autoindent = true
vim.opt.autoread = true
vim.opt.autowrite = false
vim.opt.autowriteall = false
vim.opt.background = "dark"
vim.opt.backup = false
vim.opt.clipboard = ""
vim.opt.cmdheight = 1
vim.opt.colorcolumn = { 120 }
vim.opt.completeopt = "menu,preview"
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.number = true
vim.opt.pumheight = 8
vim.opt.pumwidth = 24
vim.opt.scrolloff = 8
vim.opt.shiftround = false
vim.opt.shiftwidth = 4
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.syntax = 'yes'
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.timeout = true
vim.opt.timeoutlen = 1000
vim.opt.title = true
vim.opt.titlelen = 12
vim.opt.titleold = "neovim break"
vim.opt.titlestring = "neovim grindset"
vim.opt.undofile = true
vim.opt.undolevels = 1000
vim.opt.undodir = os.getenv('HOME') .. '/.cache/nvim/undodir'
vim.opt.visualbell = true
vim.opt.wrap = false
